# Generated by Django 3.0.7 on 2020-06-24 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookedRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('equipment', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('duration', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Calendar')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookedRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.BookedRoom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.User')),
            ],
        ),
        migrations.AddField(
            model_name='bookedroom',
            name='bookingTime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.BookingTime'),
        ),
        migrations.AddField(
            model_name='bookedroom',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Space'),
        ),
    ]
