# Generated by Django 3.0.7 on 2020-06-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_auto_20200624_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedroom',
            name='bookingTime',
        ),
        migrations.AddField(
            model_name='bookedroom',
            name='date',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planning.Calendar'),
        ),
        migrations.AddField(
            model_name='bookedroom',
            name='slot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planning.Timeslot'),
        ),
        migrations.DeleteModel(
            name='BookingTime',
        ),
    ]
